name: 'dt-project'
services:
  api:
    image: dt-project/api:latest
    env_file:
      - .env
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - 3000:3000

  webapp:
    image: dt-project/webapp:latest
    links:
      - api

  mariadb:
    image: mariadb/server
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    ports:
      - 3306:3306
    volumes:
      - 'mysql-data:/var/lib/mysql'

volumes:
  mysql-data:
    driver: local
